trigger:
  - master

schedules:
  - cron: '00 04 * * *'
    displayName: Daily Build
    branches:
      include:
        - master
    always: true

variables:
  ENV_AZURE_PIPELINE: true
  CI_NAME: 'Azure DevOps'
  CI_BRANCH: $(Build.SourceBranch)
  CI_BUILD_NUMBER: $(Build.BuildNumber)
  CI_BUILD_URL: $(Build.BuildUri)

stages:
  - stage: UnitTests
    jobs:
      - job: Windows
        pool:
          vmImage: 'windows-latest'
        steps:
          - template: azure/templates/unit-tests.yml
      - job: macOS
        pool:
          vmImage: 'macOS-10.15'
        steps:
          - template: azure/templates/unit-tests.yml
      - job: Linux
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - template: azure/templates/unit-tests.yml
  - stage: SystemTests
    dependsOn: []
    condition: eq(variables['Build.Reason'], 'Schedule')
    jobs:
      - job: Linux
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - template: azure/templates/system-tests.yml
